plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.triggers.base'
    compileSdk 34

    defaultConfig {
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = '17' }

    flavorDimensions += "trigger"
    productFlavors {
        trigger1 {
            dimension "trigger"
            applicationId "com.triggers.one"
            resValue "string", "app_name", "Zappa"
        }
        trigger2 {
            dimension "trigger"
            applicationId "com.triggers.two"
            resValue "string", "app_name", "Mingus"
        }
        trigger3 {
            dimension "trigger"
            applicationId "com.triggers.three"
            resValue "string", "app_name", "Coltrane"
        }
        trigger4 {
            dimension "trigger"
            applicationId "com.triggers.four"
            resValue "string", "app_name", "Hendrix"
        }
        trigger5 {
            dimension "trigger"
            applicationId "com.triggers.five"
            resValue "string", "app_name", "Bowie"
        }
    }

    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            def flavorName = variant.flavorName.capitalize()
            outputFileName = "Trigger-${flavorName}-${variant.buildType.name}.apk"
        }
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.13.1'
}
